# Default values for board-demoshow.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

demoui:
  name: demoui
  replicaCount: 1

  image:
    repository: docker.io/inspurboard/demoui
    tag: 0.9
    pullPolicy: Always

  service:
    type: NodePort
    port: 80


  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

democore:
  name: democore
  replicaCount: 1

  image:
    repository: docker.io/inspurboard/democore
    tag: 0.9
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 80


  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

demoworker:
  name: demoworker
  replicaCount: 2

  image:
    repository: docker.io/inspurboard/demoworker
    tag: 0.9
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 80


  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}
