# Default values for board-demoshow.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

demoui:
  name: demoui
  replicaCount: 1

  image:
    repository: 10.111.24.131:5001/demoshow_ui
    tag: latest
    pullPolicy: Always

  service:
    type: NodePort
    port: 80


  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

democore:
  name: democore
  replicaCount: 1

  image:
    repository: 10.111.24.131:5001/demoshow_democore
    tag: latest
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 80


  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

demoworker:
  name: demoworker
  replicaCount: 2

  image:
    repository: 10.111.24.131:5001/demoshow_demoworker
    tag: latest
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 80


  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}
