apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: democoreui2
  namespace: library
spec:
  ports:
  - nodePort: 30016
    port: 8080
    targetPort: 0
    name: port1
  - nodePort: 30017
    port: 80
    targetPort: 0
    name: port2
  selector:
    app: democoreui2
  type: NodePort
status:
  loadBalancer: {}
