apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "board-demoshow.democore.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "board-demoshow.name" . }}
    helm.sh/chart: {{ include "board-demoshow.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: {{ .Values.democore.name }}
spec:
  replicas: {{ .Values.democore.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "board-demoshow.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: {{ .Values.democore.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "board-demoshow.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: {{ .Values.democore.name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.democore.image.repository }}:{{ .Values.democore.image.tag }}"
          imagePullPolicy: {{ .Values.democore.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
{{ toYaml .Values.democore.resources | indent 12 }}
    {{- with .Values.democore.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.democore.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.democore.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
