apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "board-demoshow.demoui.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "board-demoshow.name" . }}
    helm.sh/chart: {{ include "board-demoshow.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: {{ .Values.demoui.name }}
spec:
  replicas: {{ .Values.demoui.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "board-demoshow.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: {{ .Values.demoui.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "board-demoshow.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: {{ .Values.demoui.name }}
    spec:
      containers:
        - name: {{ .Values.demoui.name }}
          image: "{{ .Values.demoui.image.repository }}:{{ .Values.demoui.image.tag }}"
          imagePullPolicy: {{ .Values.demoui.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - sed -i -e "s/8080/$DEMOCORE_SERVICE_PORT/g" -e "s/localhost/$DEMOCORE_SERVICE/g"  -e "s/\$http_host/$DEMOCORE_SERVICE/g" /etc/nginx/nginx.conf && nginx -g "daemon off;"
          env:
            - name: DEMOCORE_SERVICE
              value: {{ include "board-demoshow.democore.fullname" . }}
            - name: DEMOCORE_SERVICE_PORT
              value: {{ quote .Values.democore.service.port }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
{{ toYaml .Values.demoui.resources | indent 12 }}
    {{- with .Values.demoui.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.demoui.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.demoui.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
