apiVersion: v1
kind: Service
metadata:
  name: {{ include "board-demoshow.democore.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "board-demoshow.name" . }}
    helm.sh/chart: {{ include "board-demoshow.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: {{ .Values.democore.name }}
spec:
  type: {{ .Values.democore.service.type }}
  ports:
    - port: {{ .Values.democore.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "board-demoshow.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: {{ .Values.democore.name }}
